### ISSUE TITLE
interleaved symmetric mode valid packet?

### ISSUE THREAD

**Issue by aanchal4** [ietf-wg-ntp/draft-ietf-ntp-interleaved-modes#2]
In Section 3, interleaved symmetric mode, for the two bullet points we need to resolve the following two issues:
1) How does a peer know if it has received a valid packet in the interleaved mode?
2) What does a valid packet mean in this context?

**Comment by mlichvar** [comment]
A valid packet in this context is a packet that passed all NTP tests, including the check of the origin timestamp. I'll see if I can improve the text.

**Comment by mlichvar** [comment]
It should be fixed in commit cd951f2c.
